unit x32.evex_wig1;

// This unit was generated by d2p.pl script.
// Source : gas/evex-wig1-intel.d

interface

uses
  uTestCase,
  UnivDisasm.Cnsts;

procedure Test();

implementation

procedure Test();
var
  TestCase:TTestCase;
begin
  TestCase := TTestCase.Create('x32.evex_wig1');
  TestCase.Start();	
  TestCase.Arch := CPUX32;

  TestCase.testcase(0, [$62,$F2,$FD,$4F,$21,$F5                           ] , 'vpmovsxbd  zmm6{k7},xmm5'                         );
  TestCase.testcase(1, [$62,$F2,$FD,$CF,$21,$F5                           ] , 'vpmovsxbd  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(2, [$62,$F2,$FD,$4F,$21,$31                           ] , 'vpmovsxbd  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(3, [$62,$F2,$FD,$4F,$21,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxbd  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(4, [$62,$F2,$FD,$4F,$21,$72,$7F                       ] , 'vpmovsxbd  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(5, [$62,$F2,$FD,$4F,$21,$B2,$00,$08,$00,$00           ] , 'vpmovsxbd  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(6, [$62,$F2,$FD,$4F,$21,$72,$80                       ] , 'vpmovsxbd  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(7, [$62,$F2,$FD,$4F,$21,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovsxbd  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(8, [$62,$F2,$FD,$4F,$22,$F5                           ] , 'vpmovsxbq  zmm6{k7},xmm5'                         );
  TestCase.testcase(9, [$62,$F2,$FD,$CF,$22,$F5                           ] , 'vpmovsxbq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(10, [$62,$F2,$FD,$4F,$22,$31                           ] , 'vpmovsxbq  zmm6{k7},qword [ecx]'                  );
  TestCase.testcase(11, [$62,$F2,$FD,$4F,$22,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxbq  zmm6{k7},qword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(12, [$62,$F2,$FD,$4F,$22,$72,$7F                       ] , 'vpmovsxbq  zmm6{k7},qword [edx+0x3f8]'            );
  TestCase.testcase(13, [$62,$F2,$FD,$4F,$22,$B2,$00,$04,$00,$00           ] , 'vpmovsxbq  zmm6{k7},qword [edx+0x400]'            );
  TestCase.testcase(14, [$62,$F2,$FD,$4F,$22,$72,$80                       ] , 'vpmovsxbq  zmm6{k7},qword [edx-0x400]'            );
  TestCase.testcase(15, [$62,$F2,$FD,$4F,$22,$B2,$F8,$FB,$FF,$FF           ] , 'vpmovsxbq  zmm6{k7},qword [edx-0x408]'            );
  TestCase.testcase(16, [$62,$F2,$FD,$4F,$23,$F5                           ] , 'vpmovsxwd  zmm6{k7},ymm5'                         );
  TestCase.testcase(17, [$62,$F2,$FD,$CF,$23,$F5                           ] , 'vpmovsxwd  zmm6{k7}{z},ymm5'                      );
  TestCase.testcase(18, [$62,$F2,$FD,$4F,$23,$31                           ] , 'vpmovsxwd  zmm6{k7},yword [ecx]'                  );
  TestCase.testcase(19, [$62,$F2,$FD,$4F,$23,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxwd  zmm6{k7},yword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(20, [$62,$F2,$FD,$4F,$23,$72,$7F                       ] , 'vpmovsxwd  zmm6{k7},yword [edx+0xfe0]'            );
  TestCase.testcase(21, [$62,$F2,$FD,$4F,$23,$B2,$00,$10,$00,$00           ] , 'vpmovsxwd  zmm6{k7},yword [edx+0x1000]'           );
  TestCase.testcase(22, [$62,$F2,$FD,$4F,$23,$72,$80                       ] , 'vpmovsxwd  zmm6{k7},yword [edx-0x1000]'           );
  TestCase.testcase(23, [$62,$F2,$FD,$4F,$23,$B2,$E0,$EF,$FF,$FF           ] , 'vpmovsxwd  zmm6{k7},yword [edx-0x1020]'           );
  TestCase.testcase(24, [$62,$F2,$FD,$4F,$24,$F5                           ] , 'vpmovsxwq  zmm6{k7},xmm5'                         );
  TestCase.testcase(25, [$62,$F2,$FD,$CF,$24,$F5                           ] , 'vpmovsxwq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(26, [$62,$F2,$FD,$4F,$24,$31                           ] , 'vpmovsxwq  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(27, [$62,$F2,$FD,$4F,$24,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxwq  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(28, [$62,$F2,$FD,$4F,$24,$72,$7F                       ] , 'vpmovsxwq  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(29, [$62,$F2,$FD,$4F,$24,$B2,$00,$08,$00,$00           ] , 'vpmovsxwq  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(30, [$62,$F2,$FD,$4F,$24,$72,$80                       ] , 'vpmovsxwq  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(31, [$62,$F2,$FD,$4F,$24,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovsxwq  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(32, [$62,$F2,$FD,$4F,$31,$F5                           ] , 'vpmovzxbd  zmm6{k7},xmm5'                         );
  TestCase.testcase(33, [$62,$F2,$FD,$CF,$31,$F5                           ] , 'vpmovzxbd  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(34, [$62,$F2,$FD,$4F,$31,$31                           ] , 'vpmovzxbd  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(35, [$62,$F2,$FD,$4F,$31,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxbd  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(36, [$62,$F2,$FD,$4F,$31,$72,$7F                       ] , 'vpmovzxbd  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(37, [$62,$F2,$FD,$4F,$31,$B2,$00,$08,$00,$00           ] , 'vpmovzxbd  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(38, [$62,$F2,$FD,$4F,$31,$72,$80                       ] , 'vpmovzxbd  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(39, [$62,$F2,$FD,$4F,$31,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovzxbd  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(40, [$62,$F2,$FD,$4F,$32,$F5                           ] , 'vpmovzxbq  zmm6{k7},xmm5'                         );
  TestCase.testcase(41, [$62,$F2,$FD,$CF,$32,$F5                           ] , 'vpmovzxbq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(42, [$62,$F2,$FD,$4F,$32,$31                           ] , 'vpmovzxbq  zmm6{k7},qword [ecx]'                  );
  TestCase.testcase(43, [$62,$F2,$FD,$4F,$32,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxbq  zmm6{k7},qword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(44, [$62,$F2,$FD,$4F,$32,$72,$7F                       ] , 'vpmovzxbq  zmm6{k7},qword [edx+0x3f8]'            );
  TestCase.testcase(45, [$62,$F2,$FD,$4F,$32,$B2,$00,$04,$00,$00           ] , 'vpmovzxbq  zmm6{k7},qword [edx+0x400]'            );
  TestCase.testcase(46, [$62,$F2,$FD,$4F,$32,$72,$80                       ] , 'vpmovzxbq  zmm6{k7},qword [edx-0x400]'            );
  TestCase.testcase(47, [$62,$F2,$FD,$4F,$32,$B2,$F8,$FB,$FF,$FF           ] , 'vpmovzxbq  zmm6{k7},qword [edx-0x408]'            );
  TestCase.testcase(48, [$62,$F2,$FD,$4F,$33,$F5                           ] , 'vpmovzxwd  zmm6{k7},ymm5'                         );
  TestCase.testcase(49, [$62,$F2,$FD,$CF,$33,$F5                           ] , 'vpmovzxwd  zmm6{k7}{z},ymm5'                      );
  TestCase.testcase(50, [$62,$F2,$FD,$4F,$33,$31                           ] , 'vpmovzxwd  zmm6{k7},yword [ecx]'                  );
  TestCase.testcase(51, [$62,$F2,$FD,$4F,$33,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxwd  zmm6{k7},yword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(52, [$62,$F2,$FD,$4F,$33,$72,$7F                       ] , 'vpmovzxwd  zmm6{k7},yword [edx+0xfe0]'            );
  TestCase.testcase(53, [$62,$F2,$FD,$4F,$33,$B2,$00,$10,$00,$00           ] , 'vpmovzxwd  zmm6{k7},yword [edx+0x1000]'           );
  TestCase.testcase(54, [$62,$F2,$FD,$4F,$33,$72,$80                       ] , 'vpmovzxwd  zmm6{k7},yword [edx-0x1000]'           );
  TestCase.testcase(55, [$62,$F2,$FD,$4F,$33,$B2,$E0,$EF,$FF,$FF           ] , 'vpmovzxwd  zmm6{k7},yword [edx-0x1020]'           );
  TestCase.testcase(56, [$62,$F2,$FD,$4F,$34,$F5                           ] , 'vpmovzxwq  zmm6{k7},xmm5'                         );
  TestCase.testcase(57, [$62,$F2,$FD,$CF,$34,$F5                           ] , 'vpmovzxwq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(58, [$62,$F2,$FD,$4F,$34,$31                           ] , 'vpmovzxwq  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(59, [$62,$F2,$FD,$4F,$34,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxwq  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(60, [$62,$F2,$FD,$4F,$34,$72,$7F                       ] , 'vpmovzxwq  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(61, [$62,$F2,$FD,$4F,$34,$B2,$00,$08,$00,$00           ] , 'vpmovzxwq  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(62, [$62,$F2,$FD,$4F,$34,$72,$80                       ] , 'vpmovzxwq  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(63, [$62,$F2,$FD,$4F,$34,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovzxwq  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(64, [$62,$F2,$FD,$4F,$21,$F5                           ] , 'vpmovsxbd  zmm6{k7},xmm5'                         );
  TestCase.testcase(65, [$62,$F2,$FD,$CF,$21,$F5                           ] , 'vpmovsxbd  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(66, [$62,$F2,$FD,$4F,$21,$31                           ] , 'vpmovsxbd  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(67, [$62,$F2,$FD,$4F,$21,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxbd  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(68, [$62,$F2,$FD,$4F,$21,$72,$7F                       ] , 'vpmovsxbd  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(69, [$62,$F2,$FD,$4F,$21,$B2,$00,$08,$00,$00           ] , 'vpmovsxbd  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(70, [$62,$F2,$FD,$4F,$21,$72,$80                       ] , 'vpmovsxbd  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(71, [$62,$F2,$FD,$4F,$21,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovsxbd  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(72, [$62,$F2,$FD,$4F,$22,$F5                           ] , 'vpmovsxbq  zmm6{k7},xmm5'                         );
  TestCase.testcase(73, [$62,$F2,$FD,$CF,$22,$F5                           ] , 'vpmovsxbq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(74, [$62,$F2,$FD,$4F,$22,$31                           ] , 'vpmovsxbq  zmm6{k7},qword [ecx]'                  );
  TestCase.testcase(75, [$62,$F2,$FD,$4F,$22,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxbq  zmm6{k7},qword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(76, [$62,$F2,$FD,$4F,$22,$72,$7F                       ] , 'vpmovsxbq  zmm6{k7},qword [edx+0x3f8]'            );
  TestCase.testcase(77, [$62,$F2,$FD,$4F,$22,$B2,$00,$04,$00,$00           ] , 'vpmovsxbq  zmm6{k7},qword [edx+0x400]'            );
  TestCase.testcase(78, [$62,$F2,$FD,$4F,$22,$72,$80                       ] , 'vpmovsxbq  zmm6{k7},qword [edx-0x400]'            );
  TestCase.testcase(79, [$62,$F2,$FD,$4F,$22,$B2,$F8,$FB,$FF,$FF           ] , 'vpmovsxbq  zmm6{k7},qword [edx-0x408]'            );
  TestCase.testcase(80, [$62,$F2,$FD,$4F,$23,$F5                           ] , 'vpmovsxwd  zmm6{k7},ymm5'                         );
  TestCase.testcase(81, [$62,$F2,$FD,$CF,$23,$F5                           ] , 'vpmovsxwd  zmm6{k7}{z},ymm5'                      );
  TestCase.testcase(82, [$62,$F2,$FD,$4F,$23,$31                           ] , 'vpmovsxwd  zmm6{k7},yword [ecx]'                  );
  TestCase.testcase(83, [$62,$F2,$FD,$4F,$23,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxwd  zmm6{k7},yword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(84, [$62,$F2,$FD,$4F,$23,$72,$7F                       ] , 'vpmovsxwd  zmm6{k7},yword [edx+0xfe0]'            );
  TestCase.testcase(85, [$62,$F2,$FD,$4F,$23,$B2,$00,$10,$00,$00           ] , 'vpmovsxwd  zmm6{k7},yword [edx+0x1000]'           );
  TestCase.testcase(86, [$62,$F2,$FD,$4F,$23,$72,$80                       ] , 'vpmovsxwd  zmm6{k7},yword [edx-0x1000]'           );
  TestCase.testcase(87, [$62,$F2,$FD,$4F,$23,$B2,$E0,$EF,$FF,$FF           ] , 'vpmovsxwd  zmm6{k7},yword [edx-0x1020]'           );
  TestCase.testcase(88, [$62,$F2,$FD,$4F,$24,$F5                           ] , 'vpmovsxwq  zmm6{k7},xmm5'                         );
  TestCase.testcase(89, [$62,$F2,$FD,$CF,$24,$F5                           ] , 'vpmovsxwq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(90, [$62,$F2,$FD,$4F,$24,$31                           ] , 'vpmovsxwq  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(91, [$62,$F2,$FD,$4F,$24,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovsxwq  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(92, [$62,$F2,$FD,$4F,$24,$72,$7F                       ] , 'vpmovsxwq  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(93, [$62,$F2,$FD,$4F,$24,$B2,$00,$08,$00,$00           ] , 'vpmovsxwq  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(94, [$62,$F2,$FD,$4F,$24,$72,$80                       ] , 'vpmovsxwq  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(95, [$62,$F2,$FD,$4F,$24,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovsxwq  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(96, [$62,$F2,$FD,$4F,$31,$F5                           ] , 'vpmovzxbd  zmm6{k7},xmm5'                         );
  TestCase.testcase(97, [$62,$F2,$FD,$CF,$31,$F5                           ] , 'vpmovzxbd  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(98, [$62,$F2,$FD,$4F,$31,$31                           ] , 'vpmovzxbd  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(99, [$62,$F2,$FD,$4F,$31,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxbd  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(100, [$62,$F2,$FD,$4F,$31,$72,$7F                       ] , 'vpmovzxbd  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(101, [$62,$F2,$FD,$4F,$31,$B2,$00,$08,$00,$00           ] , 'vpmovzxbd  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(102, [$62,$F2,$FD,$4F,$31,$72,$80                       ] , 'vpmovzxbd  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(103, [$62,$F2,$FD,$4F,$31,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovzxbd  zmm6{k7},oword [edx-0x810]'            );
  TestCase.testcase(104, [$62,$F2,$FD,$4F,$32,$F5                           ] , 'vpmovzxbq  zmm6{k7},xmm5'                         );
  TestCase.testcase(105, [$62,$F2,$FD,$CF,$32,$F5                           ] , 'vpmovzxbq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(106, [$62,$F2,$FD,$4F,$32,$31                           ] , 'vpmovzxbq  zmm6{k7},qword [ecx]'                  );
  TestCase.testcase(107, [$62,$F2,$FD,$4F,$32,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxbq  zmm6{k7},qword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(108, [$62,$F2,$FD,$4F,$32,$72,$7F                       ] , 'vpmovzxbq  zmm6{k7},qword [edx+0x3f8]'            );
  TestCase.testcase(109, [$62,$F2,$FD,$4F,$32,$B2,$00,$04,$00,$00           ] , 'vpmovzxbq  zmm6{k7},qword [edx+0x400]'            );
  TestCase.testcase(110, [$62,$F2,$FD,$4F,$32,$72,$80                       ] , 'vpmovzxbq  zmm6{k7},qword [edx-0x400]'            );
  TestCase.testcase(111, [$62,$F2,$FD,$4F,$32,$B2,$F8,$FB,$FF,$FF           ] , 'vpmovzxbq  zmm6{k7},qword [edx-0x408]'            );
  TestCase.testcase(112, [$62,$F2,$FD,$4F,$33,$F5                           ] , 'vpmovzxwd  zmm6{k7},ymm5'                         );
  TestCase.testcase(113, [$62,$F2,$FD,$CF,$33,$F5                           ] , 'vpmovzxwd  zmm6{k7}{z},ymm5'                      );
  TestCase.testcase(114, [$62,$F2,$FD,$4F,$33,$31                           ] , 'vpmovzxwd  zmm6{k7},yword [ecx]'                  );
  TestCase.testcase(115, [$62,$F2,$FD,$4F,$33,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxwd  zmm6{k7},yword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(116, [$62,$F2,$FD,$4F,$33,$72,$7F                       ] , 'vpmovzxwd  zmm6{k7},yword [edx+0xfe0]'            );
  TestCase.testcase(117, [$62,$F2,$FD,$4F,$33,$B2,$00,$10,$00,$00           ] , 'vpmovzxwd  zmm6{k7},yword [edx+0x1000]'           );
  TestCase.testcase(118, [$62,$F2,$FD,$4F,$33,$72,$80                       ] , 'vpmovzxwd  zmm6{k7},yword [edx-0x1000]'           );
  TestCase.testcase(119, [$62,$F2,$FD,$4F,$33,$B2,$E0,$EF,$FF,$FF           ] , 'vpmovzxwd  zmm6{k7},yword [edx-0x1020]'           );
  TestCase.testcase(120, [$62,$F2,$FD,$4F,$34,$F5                           ] , 'vpmovzxwq  zmm6{k7},xmm5'                         );
  TestCase.testcase(121, [$62,$F2,$FD,$CF,$34,$F5                           ] , 'vpmovzxwq  zmm6{k7}{z},xmm5'                      );
  TestCase.testcase(122, [$62,$F2,$FD,$4F,$34,$31                           ] , 'vpmovzxwq  zmm6{k7},oword [ecx]'                  );
  TestCase.testcase(123, [$62,$F2,$FD,$4F,$34,$B4,$F4,$C0,$1D,$FE,$FF       ] , 'vpmovzxwq  zmm6{k7},oword [esp+esi*8-0x1e240]'    );
  TestCase.testcase(124, [$62,$F2,$FD,$4F,$34,$72,$7F                       ] , 'vpmovzxwq  zmm6{k7},oword [edx+0x7f0]'            );
  TestCase.testcase(125, [$62,$F2,$FD,$4F,$34,$B2,$00,$08,$00,$00           ] , 'vpmovzxwq  zmm6{k7},oword [edx+0x800]'            );
  TestCase.testcase(126, [$62,$F2,$FD,$4F,$34,$72,$80                       ] , 'vpmovzxwq  zmm6{k7},oword [edx-0x800]'            );
  TestCase.testcase(127, [$62,$F2,$FD,$4F,$34,$B2,$F0,$F7,$FF,$FF           ] , 'vpmovzxwq  zmm6{k7},oword [edx-0x810]'            );
  TestCase.Stop();
  TestCase.SaveToFile('../../../log/x32.evex_wig1.log');
end;

end.