unit x32.bmi;

// This unit was generated by d2p.pl script.
// Source : gas/bmi-intel.d

interface

uses
  uTestCase,
  UnivDisasm.Cnsts;

procedure Test();

implementation

procedure Test();
var
  TestCase:TTestCase;
begin
  TestCase := TTestCase.Create('x32.bmi');
  TestCase.Start();	
  TestCase.Arch := CPUX32;

  TestCase.testcase(0, [$66,$F3,$0F,$BC,$D8                               ] , 'tzcnt  bx,ax'                                     );
  TestCase.testcase(1, [$66,$F3,$0F,$BC,$19                               ] , 'tzcnt  bx,word [ecx]'                             );
  TestCase.testcase(2, [$C4,$E2,$60,$F2,$F0                               ] , 'andn  esi,ebx,eax'                                );
  TestCase.testcase(3, [$C4,$E2,$60,$F2,$31                               ] , 'andn  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(4, [$C4,$E2,$78,$F7,$F3                               ] , 'bextr  esi,ebx,eax'                               );
  TestCase.testcase(5, [$C4,$E2,$60,$F7,$31                               ] , 'bextr  esi,dword [ecx],ebx'                       );
  TestCase.testcase(6, [$F3,$0F,$BC,$D8                                   ] , 'tzcnt  ebx,eax'                                   );
  TestCase.testcase(7, [$F3,$0F,$BC,$19                                   ] , 'tzcnt  ebx,dword [ecx]'                           );
  TestCase.testcase(8, [$C4,$E2,$60,$F3,$D8                               ] , 'blsi  ebx,eax'                                    );
  TestCase.testcase(9, [$C4,$E2,$60,$F3,$19                               ] , 'blsi  ebx,dword [ecx]'                            );
  TestCase.testcase(10, [$C4,$E2,$60,$F3,$D0                               ] , 'blsmsk  ebx,eax'                                  );
  TestCase.testcase(11, [$C4,$E2,$60,$F3,$11                               ] , 'blsmsk  ebx,dword [ecx]'                          );
  TestCase.testcase(12, [$C4,$E2,$60,$F3,$C8                               ] , 'blsr  ebx,eax'                                    );
  TestCase.testcase(13, [$C4,$E2,$60,$F3,$09                               ] , 'blsr  ebx,dword [ecx]'                            );
  TestCase.testcase(14, [$66,$F3,$0F,$BC,$D8                               ] , 'tzcnt  bx,ax'                                     );
  TestCase.testcase(15, [$66,$F3,$0F,$BC,$19                               ] , 'tzcnt  bx,word [ecx]'                             );
  TestCase.testcase(16, [$66,$F3,$0F,$BC,$19                               ] , 'tzcnt  bx,word [ecx]'                             );
  TestCase.testcase(17, [$C4,$E2,$60,$F2,$F0                               ] , 'andn  esi,ebx,eax'                                );
  TestCase.testcase(18, [$C4,$E2,$60,$F2,$31                               ] , 'andn  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(19, [$C4,$E2,$60,$F2,$31                               ] , 'andn  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(20, [$C4,$E2,$78,$F7,$F3                               ] , 'bextr  esi,ebx,eax'                               );
  TestCase.testcase(21, [$C4,$E2,$60,$F7,$31                               ] , 'bextr  esi,dword [ecx],ebx'                       );
  TestCase.testcase(22, [$C4,$E2,$60,$F7,$31                               ] , 'bextr  esi,dword [ecx],ebx'                       );
  TestCase.testcase(23, [$F3,$0F,$BC,$D8                                   ] , 'tzcnt  ebx,eax'                                   );
  TestCase.testcase(24, [$F3,$0F,$BC,$19                                   ] , 'tzcnt  ebx,dword [ecx]'                           );
  TestCase.testcase(25, [$F3,$0F,$BC,$19                                   ] , 'tzcnt  ebx,dword [ecx]'                           );
  TestCase.testcase(26, [$C4,$E2,$60,$F3,$D8                               ] , 'blsi  ebx,eax'                                    );
  TestCase.testcase(27, [$C4,$E2,$60,$F3,$19                               ] , 'blsi  ebx,dword [ecx]'                            );
  TestCase.testcase(28, [$C4,$E2,$60,$F3,$19                               ] , 'blsi  ebx,dword [ecx]'                            );
  TestCase.testcase(29, [$C4,$E2,$60,$F3,$D0                               ] , 'blsmsk  ebx,eax'                                  );
  TestCase.testcase(30, [$C4,$E2,$60,$F3,$11                               ] , 'blsmsk  ebx,dword [ecx]'                          );
  TestCase.testcase(31, [$C4,$E2,$60,$F3,$11                               ] , 'blsmsk  ebx,dword [ecx]'                          );
  TestCase.testcase(32, [$C4,$E2,$60,$F3,$C8                               ] , 'blsr  ebx,eax'                                    );
  TestCase.testcase(33, [$C4,$E2,$60,$F3,$09                               ] , 'blsr  ebx,dword [ecx]'                            );
  TestCase.testcase(34, [$C4,$E2,$60,$F3,$09                               ] , 'blsr  ebx,dword [ecx]'                            );
  TestCase.Stop();
  TestCase.SaveToFile('../../../log/x32.bmi.log');
end;

end.