unit x32.bmi2;

// This unit was generated by d2p.pl script.
// Source : gas/bmi2-intel.d

interface

uses
  uTestCase,
  UnivDisasm.Cnsts;

procedure Test();

implementation

procedure Test();
var
  TestCase:TTestCase;
begin
  TestCase := TTestCase.Create('x32.bmi2');
  TestCase.Start();	
  TestCase.Arch := CPUX32;

  TestCase.testcase(0, [$C4,$E3,$7B,$F0,$D8,$07                           ] , 'rorx  ebx,eax,0x7'                                );
  TestCase.testcase(1, [$C4,$E3,$7B,$F0,$19,$07                           ] , 'rorx  ebx,dword [ecx],0x7'                        );
  TestCase.testcase(2, [$C4,$E2,$63,$F6,$F0                               ] , 'mulx  esi,ebx,eax'                                );
  TestCase.testcase(3, [$C4,$E2,$63,$F6,$31                               ] , 'mulx  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(4, [$C4,$E2,$63,$F5,$F0                               ] , 'pdep  esi,ebx,eax'                                );
  TestCase.testcase(5, [$C4,$E2,$63,$F5,$31                               ] , 'pdep  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(6, [$C4,$E2,$62,$F5,$F0                               ] , 'pext  esi,ebx,eax'                                );
  TestCase.testcase(7, [$C4,$E2,$62,$F5,$31                               ] , 'pext  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(8, [$C4,$E2,$78,$F5,$F3                               ] , 'bzhi  esi,ebx,eax'                                );
  TestCase.testcase(9, [$C4,$E2,$60,$F5,$31                               ] , 'bzhi  esi,dword [ecx],ebx'                        );
  TestCase.testcase(10, [$C4,$E2,$7A,$F7,$F3                               ] , 'sarx  esi,ebx,eax'                                );
  TestCase.testcase(11, [$C4,$E2,$62,$F7,$31                               ] , 'sarx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(12, [$C4,$E2,$79,$F7,$F3                               ] , 'shlx  esi,ebx,eax'                                );
  TestCase.testcase(13, [$C4,$E2,$61,$F7,$31                               ] , 'shlx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(14, [$C4,$E2,$7B,$F7,$F3                               ] , 'shrx  esi,ebx,eax'                                );
  TestCase.testcase(15, [$C4,$E2,$63,$F7,$31                               ] , 'shrx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(16, [$C4,$E3,$7B,$F0,$D8,$07                           ] , 'rorx  ebx,eax,0x7'                                );
  TestCase.testcase(17, [$C4,$E3,$7B,$F0,$19,$07                           ] , 'rorx  ebx,dword [ecx],0x7'                        );
  TestCase.testcase(18, [$C4,$E3,$7B,$F0,$19,$07                           ] , 'rorx  ebx,dword [ecx],0x7'                        );
  TestCase.testcase(19, [$C4,$E2,$63,$F6,$F0                               ] , 'mulx  esi,ebx,eax'                                );
  TestCase.testcase(20, [$C4,$E2,$63,$F6,$31                               ] , 'mulx  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(21, [$C4,$E2,$63,$F6,$31                               ] , 'mulx  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(22, [$C4,$E2,$63,$F5,$F0                               ] , 'pdep  esi,ebx,eax'                                );
  TestCase.testcase(23, [$C4,$E2,$63,$F5,$31                               ] , 'pdep  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(24, [$C4,$E2,$63,$F5,$31                               ] , 'pdep  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(25, [$C4,$E2,$62,$F5,$F0                               ] , 'pext  esi,ebx,eax'                                );
  TestCase.testcase(26, [$C4,$E2,$62,$F5,$31                               ] , 'pext  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(27, [$C4,$E2,$62,$F5,$31                               ] , 'pext  esi,ebx,dword [ecx]'                        );
  TestCase.testcase(28, [$C4,$E2,$78,$F5,$F3                               ] , 'bzhi  esi,ebx,eax'                                );
  TestCase.testcase(29, [$C4,$E2,$60,$F5,$31                               ] , 'bzhi  esi,dword [ecx],ebx'                        );
  TestCase.testcase(30, [$C4,$E2,$60,$F5,$31                               ] , 'bzhi  esi,dword [ecx],ebx'                        );
  TestCase.testcase(31, [$C4,$E2,$7A,$F7,$F3                               ] , 'sarx  esi,ebx,eax'                                );
  TestCase.testcase(32, [$C4,$E2,$62,$F7,$31                               ] , 'sarx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(33, [$C4,$E2,$62,$F7,$31                               ] , 'sarx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(34, [$C4,$E2,$79,$F7,$F3                               ] , 'shlx  esi,ebx,eax'                                );
  TestCase.testcase(35, [$C4,$E2,$61,$F7,$31                               ] , 'shlx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(36, [$C4,$E2,$61,$F7,$31                               ] , 'shlx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(37, [$C4,$E2,$7B,$F7,$F3                               ] , 'shrx  esi,ebx,eax'                                );
  TestCase.testcase(38, [$C4,$E2,$63,$F7,$31                               ] , 'shrx  esi,dword [ecx],ebx'                        );
  TestCase.testcase(39, [$C4,$E2,$63,$F7,$31                               ] , 'shrx  esi,dword [ecx],ebx'                        );
  TestCase.Stop();
  TestCase.SaveToFile('../../../log/x32.bmi2.log');
end;

end.