unit x64.avx512pf;

// This unit was generated by d2p.pl script.
// Source : gas/x86-64-avx512pf-intel.d

interface

uses
  uTestCase,
  UnivDisasm.Cnsts;

procedure Test();

implementation

procedure Test();
var
  TestCase:TTestCase;
begin
  TestCase := TTestCase.Create('x64.avx512pf');
  TestCase.Start();	
  TestCase.Arch := CPUX64;

  TestCase.testcase(0, [$62,$92,$FD,$41,$C6,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0dpd  zword [r14+ymm31*8+0x7b]{k1}'      );
  TestCase.testcase(1, [$62,$92,$FD,$41,$C6,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0dpd  zword [r14+ymm31*8+0x7b]{k1}'      );
  TestCase.testcase(2, [$62,$92,$FD,$41,$C6,$4C,$39,$20                   ] , 'vgatherpf0dpd  zword [r9+ymm31*1+0x100]{k1}'      );
  TestCase.testcase(3, [$62,$B2,$FD,$41,$C6,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0dpd  zword [rcx+ymm31*4+0x400]{k1}'     );
  TestCase.testcase(4, [$62,$92,$7D,$41,$C6,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0dps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(5, [$62,$92,$7D,$41,$C6,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0dps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(6, [$62,$92,$7D,$41,$C6,$4C,$39,$40                   ] , 'vgatherpf0dps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(7, [$62,$B2,$7D,$41,$C6,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0dps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(8, [$62,$92,$FD,$41,$C7,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0qpd  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(9, [$62,$92,$FD,$41,$C7,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0qpd  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(10, [$62,$92,$FD,$41,$C7,$4C,$39,$20                   ] , 'vgatherpf0qpd  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(11, [$62,$B2,$FD,$41,$C7,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0qpd  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(12, [$62,$92,$7D,$41,$C7,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0qps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(13, [$62,$92,$7D,$41,$C7,$8C,$FE,$7B,$00,$00,$00       ] , 'vgatherpf0qps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(14, [$62,$92,$7D,$41,$C7,$4C,$39,$40                   ] , 'vgatherpf0qps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(15, [$62,$B2,$7D,$41,$C7,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0qps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(16, [$62,$92,$FD,$41,$C6,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1dpd  zword [r14+ymm31*8+0x7b]{k1}'      );
  TestCase.testcase(17, [$62,$92,$FD,$41,$C6,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1dpd  zword [r14+ymm31*8+0x7b]{k1}'      );
  TestCase.testcase(18, [$62,$92,$FD,$41,$C6,$54,$39,$20                   ] , 'vgatherpf1dpd  zword [r9+ymm31*1+0x100]{k1}'      );
  TestCase.testcase(19, [$62,$B2,$FD,$41,$C6,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1dpd  zword [rcx+ymm31*4+0x400]{k1}'     );
  TestCase.testcase(20, [$62,$92,$7D,$41,$C6,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1dps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(21, [$62,$92,$7D,$41,$C6,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1dps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(22, [$62,$92,$7D,$41,$C6,$54,$39,$40                   ] , 'vgatherpf1dps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(23, [$62,$B2,$7D,$41,$C6,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1dps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(24, [$62,$92,$FD,$41,$C7,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1qpd  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(25, [$62,$92,$FD,$41,$C7,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1qpd  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(26, [$62,$92,$FD,$41,$C7,$54,$39,$20                   ] , 'vgatherpf1qpd  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(27, [$62,$B2,$FD,$41,$C7,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1qpd  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(28, [$62,$92,$7D,$41,$C7,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1qps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(29, [$62,$92,$7D,$41,$C7,$94,$FE,$7B,$00,$00,$00       ] , 'vgatherpf1qps  zword [r14+zmm31*8+0x7b]{k1}'      );
  TestCase.testcase(30, [$62,$92,$7D,$41,$C7,$54,$39,$40                   ] , 'vgatherpf1qps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(31, [$62,$B2,$7D,$41,$C7,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1qps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(32, [$62,$92,$FD,$41,$C6,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0dpd  zword [r14+ymm31*8+0x7b]{k1}'     );
  TestCase.testcase(33, [$62,$92,$FD,$41,$C6,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0dpd  zword [r14+ymm31*8+0x7b]{k1}'     );
  TestCase.testcase(34, [$62,$92,$FD,$41,$C6,$6C,$39,$20                   ] , 'vscatterpf0dpd  zword [r9+ymm31*1+0x100]{k1}'     );
  TestCase.testcase(35, [$62,$B2,$FD,$41,$C6,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0dpd  zword [rcx+ymm31*4+0x400]{k1}'    );
  TestCase.testcase(36, [$62,$92,$7D,$41,$C6,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0dps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(37, [$62,$92,$7D,$41,$C6,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0dps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(38, [$62,$92,$7D,$41,$C6,$6C,$39,$40                   ] , 'vscatterpf0dps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(39, [$62,$B2,$7D,$41,$C6,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0dps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(40, [$62,$92,$FD,$41,$C7,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0qpd  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(41, [$62,$92,$FD,$41,$C7,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0qpd  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(42, [$62,$92,$FD,$41,$C7,$6C,$39,$20                   ] , 'vscatterpf0qpd  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(43, [$62,$B2,$FD,$41,$C7,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0qpd  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(44, [$62,$92,$7D,$41,$C7,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0qps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(45, [$62,$92,$7D,$41,$C7,$AC,$FE,$7B,$00,$00,$00       ] , 'vscatterpf0qps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(46, [$62,$92,$7D,$41,$C7,$6C,$39,$40                   ] , 'vscatterpf0qps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(47, [$62,$B2,$7D,$41,$C7,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0qps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(48, [$62,$92,$FD,$41,$C6,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1dpd  zword [r14+ymm31*8+0x7b]{k1}'     );
  TestCase.testcase(49, [$62,$92,$FD,$41,$C6,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1dpd  zword [r14+ymm31*8+0x7b]{k1}'     );
  TestCase.testcase(50, [$62,$92,$FD,$41,$C6,$74,$39,$20                   ] , 'vscatterpf1dpd  zword [r9+ymm31*1+0x100]{k1}'     );
  TestCase.testcase(51, [$62,$B2,$FD,$41,$C6,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1dpd  zword [rcx+ymm31*4+0x400]{k1}'    );
  TestCase.testcase(52, [$62,$92,$7D,$41,$C6,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1dps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(53, [$62,$92,$7D,$41,$C6,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1dps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(54, [$62,$92,$7D,$41,$C6,$74,$39,$40                   ] , 'vscatterpf1dps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(55, [$62,$B2,$7D,$41,$C6,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1dps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(56, [$62,$92,$FD,$41,$C7,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1qpd  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(57, [$62,$92,$FD,$41,$C7,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1qpd  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(58, [$62,$92,$FD,$41,$C7,$74,$39,$20                   ] , 'vscatterpf1qpd  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(59, [$62,$B2,$FD,$41,$C7,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1qpd  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(60, [$62,$92,$7D,$41,$C7,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1qps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(61, [$62,$92,$7D,$41,$C7,$B4,$FE,$7B,$00,$00,$00       ] , 'vscatterpf1qps  zword [r14+zmm31*8+0x7b]{k1}'     );
  TestCase.testcase(62, [$62,$92,$7D,$41,$C7,$74,$39,$40                   ] , 'vscatterpf1qps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(63, [$62,$B2,$7D,$41,$C7,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1qps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(64, [$0F,$0D,$11                                       ] , 'prefetchwt1  byte [rcx]'                          );
  TestCase.testcase(65, [$42,$0F,$0D,$94,$F0,$23,$01,$00,$00               ] , 'prefetchwt1  byte [rax+r14*8+0x123]'              );
  TestCase.testcase(66, [$62,$92,$FD,$41,$C6,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0dpd  zword [r14+ymm31*8-0x7b]{k1}'      );
  TestCase.testcase(67, [$62,$92,$FD,$41,$C6,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0dpd  zword [r14+ymm31*8-0x7b]{k1}'      );
  TestCase.testcase(68, [$62,$92,$FD,$41,$C6,$4C,$39,$20                   ] , 'vgatherpf0dpd  zword [r9+ymm31*1+0x100]{k1}'      );
  TestCase.testcase(69, [$62,$B2,$FD,$41,$C6,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0dpd  zword [rcx+ymm31*4+0x400]{k1}'     );
  TestCase.testcase(70, [$62,$92,$7D,$41,$C6,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0dps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(71, [$62,$92,$7D,$41,$C6,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0dps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(72, [$62,$92,$7D,$41,$C6,$4C,$39,$40                   ] , 'vgatherpf0dps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(73, [$62,$B2,$7D,$41,$C6,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0dps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(74, [$62,$92,$FD,$41,$C7,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0qpd  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(75, [$62,$92,$FD,$41,$C7,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0qpd  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(76, [$62,$92,$FD,$41,$C7,$4C,$39,$20                   ] , 'vgatherpf0qpd  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(77, [$62,$B2,$FD,$41,$C7,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0qpd  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(78, [$62,$92,$7D,$41,$C7,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0qps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(79, [$62,$92,$7D,$41,$C7,$8C,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf0qps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(80, [$62,$92,$7D,$41,$C7,$4C,$39,$40                   ] , 'vgatherpf0qps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(81, [$62,$B2,$7D,$41,$C7,$8C,$B9,$00,$04,$00,$00       ] , 'vgatherpf0qps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(82, [$62,$92,$FD,$41,$C6,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1dpd  zword [r14+ymm31*8-0x7b]{k1}'      );
  TestCase.testcase(83, [$62,$92,$FD,$41,$C6,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1dpd  zword [r14+ymm31*8-0x7b]{k1}'      );
  TestCase.testcase(84, [$62,$92,$FD,$41,$C6,$54,$39,$20                   ] , 'vgatherpf1dpd  zword [r9+ymm31*1+0x100]{k1}'      );
  TestCase.testcase(85, [$62,$B2,$FD,$41,$C6,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1dpd  zword [rcx+ymm31*4+0x400]{k1}'     );
  TestCase.testcase(86, [$62,$92,$7D,$41,$C6,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1dps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(87, [$62,$92,$7D,$41,$C6,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1dps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(88, [$62,$92,$7D,$41,$C6,$54,$39,$40                   ] , 'vgatherpf1dps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(89, [$62,$B2,$7D,$41,$C6,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1dps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(90, [$62,$92,$FD,$41,$C7,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1qpd  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(91, [$62,$92,$FD,$41,$C7,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1qpd  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(92, [$62,$92,$FD,$41,$C7,$54,$39,$20                   ] , 'vgatherpf1qpd  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(93, [$62,$B2,$FD,$41,$C7,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1qpd  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(94, [$62,$92,$7D,$41,$C7,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1qps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(95, [$62,$92,$7D,$41,$C7,$94,$FE,$85,$FF,$FF,$FF       ] , 'vgatherpf1qps  zword [r14+zmm31*8-0x7b]{k1}'      );
  TestCase.testcase(96, [$62,$92,$7D,$41,$C7,$54,$39,$40                   ] , 'vgatherpf1qps  zword [r9+zmm31*1+0x100]{k1}'      );
  TestCase.testcase(97, [$62,$B2,$7D,$41,$C7,$94,$B9,$00,$04,$00,$00       ] , 'vgatherpf1qps  zword [rcx+zmm31*4+0x400]{k1}'     );
  TestCase.testcase(98, [$62,$92,$FD,$41,$C6,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0dpd  zword [r14+ymm31*8-0x7b]{k1}'     );
  TestCase.testcase(99, [$62,$92,$FD,$41,$C6,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0dpd  zword [r14+ymm31*8-0x7b]{k1}'     );
  TestCase.testcase(100, [$62,$92,$FD,$41,$C6,$6C,$39,$20                   ] , 'vscatterpf0dpd  zword [r9+ymm31*1+0x100]{k1}'     );
  TestCase.testcase(101, [$62,$B2,$FD,$41,$C6,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0dpd  zword [rcx+ymm31*4+0x400]{k1}'    );
  TestCase.testcase(102, [$62,$92,$7D,$41,$C6,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0dps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(103, [$62,$92,$7D,$41,$C6,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0dps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(104, [$62,$92,$7D,$41,$C6,$6C,$39,$40                   ] , 'vscatterpf0dps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(105, [$62,$B2,$7D,$41,$C6,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0dps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(106, [$62,$92,$FD,$41,$C7,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0qpd  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(107, [$62,$92,$FD,$41,$C7,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0qpd  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(108, [$62,$92,$FD,$41,$C7,$6C,$39,$20                   ] , 'vscatterpf0qpd  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(109, [$62,$B2,$FD,$41,$C7,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0qpd  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(110, [$62,$92,$7D,$41,$C7,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0qps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(111, [$62,$92,$7D,$41,$C7,$AC,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf0qps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(112, [$62,$92,$7D,$41,$C7,$6C,$39,$40                   ] , 'vscatterpf0qps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(113, [$62,$B2,$7D,$41,$C7,$AC,$B9,$00,$04,$00,$00       ] , 'vscatterpf0qps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(114, [$62,$92,$FD,$41,$C6,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1dpd  zword [r14+ymm31*8-0x7b]{k1}'     );
  TestCase.testcase(115, [$62,$92,$FD,$41,$C6,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1dpd  zword [r14+ymm31*8-0x7b]{k1}'     );
  TestCase.testcase(116, [$62,$92,$FD,$41,$C6,$74,$39,$20                   ] , 'vscatterpf1dpd  zword [r9+ymm31*1+0x100]{k1}'     );
  TestCase.testcase(117, [$62,$B2,$FD,$41,$C6,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1dpd  zword [rcx+ymm31*4+0x400]{k1}'    );
  TestCase.testcase(118, [$62,$92,$7D,$41,$C6,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1dps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(119, [$62,$92,$7D,$41,$C6,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1dps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(120, [$62,$92,$7D,$41,$C6,$74,$39,$40                   ] , 'vscatterpf1dps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(121, [$62,$B2,$7D,$41,$C6,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1dps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(122, [$62,$92,$FD,$41,$C7,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1qpd  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(123, [$62,$92,$FD,$41,$C7,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1qpd  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(124, [$62,$92,$FD,$41,$C7,$74,$39,$20                   ] , 'vscatterpf1qpd  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(125, [$62,$B2,$FD,$41,$C7,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1qpd  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(126, [$62,$92,$7D,$41,$C7,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1qps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(127, [$62,$92,$7D,$41,$C7,$B4,$FE,$85,$FF,$FF,$FF       ] , 'vscatterpf1qps  zword [r14+zmm31*8-0x7b]{k1}'     );
  TestCase.testcase(128, [$62,$92,$7D,$41,$C7,$74,$39,$40                   ] , 'vscatterpf1qps  zword [r9+zmm31*1+0x100]{k1}'     );
  TestCase.testcase(129, [$62,$B2,$7D,$41,$C7,$B4,$B9,$00,$04,$00,$00       ] , 'vscatterpf1qps  zword [rcx+zmm31*4+0x400]{k1}'    );
  TestCase.testcase(130, [$0F,$0D,$11                                       ] , 'prefetchwt1  byte [rcx]'                          );
  TestCase.testcase(131, [$42,$0F,$0D,$94,$F0,$34,$12,$00,$00               ] , 'prefetchwt1  byte [rax+r14*8+0x1234]'             );
  TestCase.Stop();
  TestCase.SaveToFile('../../../log/x64.avx512pf.log');
end;

end.