unit x64.sse4_2;

// This unit was generated by d2p.pl script.
// Source : gas/x86-64-sse4_2-intel.d

interface

uses
  uTestCase,
  UnivDisasm.Cnsts;

procedure Test();

implementation

procedure Test();
var
  TestCase:TTestCase;
begin
  TestCase := TTestCase.Create('x64.sse4_2');
  TestCase.Start();	
  TestCase.Arch := CPUX64;

  TestCase.testcase(0, [$F2,$0F,$38,$F0,$D9                               ] , 'crc32  ebx,cl'                                    );
  TestCase.testcase(1, [$F2,$48,$0F,$38,$F0,$D9                           ] , 'crc32  rbx,cl'                                    );
  TestCase.testcase(2, [$66,$F2,$0F,$38,$F1,$D9                           ] , 'crc32  ebx,cx'                                    );
  TestCase.testcase(3, [$F2,$0F,$38,$F1,$D9                               ] , 'crc32  ebx,ecx'                                   );
  TestCase.testcase(4, [$F2,$48,$0F,$38,$F1,$D9                           ] , 'crc32  rbx,rcx'                                   );
  TestCase.testcase(5, [$F2,$0F,$38,$F0,$19                               ] , 'crc32  ebx,byte [rcx]'                            );
  TestCase.testcase(6, [$66,$F2,$0F,$38,$F1,$19                           ] , 'crc32  ebx,word [rcx]'                            );
  TestCase.testcase(7, [$F2,$0F,$38,$F1,$19                               ] , 'crc32  ebx,dword [rcx]'                           );
  TestCase.testcase(8, [$F2,$48,$0F,$38,$F1,$19                           ] , 'crc32  rbx,qword [rcx]'                           );
  TestCase.testcase(9, [$F2,$0F,$38,$F0,$D9                               ] , 'crc32  ebx,cl'                                    );
  TestCase.testcase(10, [$F2,$48,$0F,$38,$F0,$D9                           ] , 'crc32  rbx,cl'                                    );
  TestCase.testcase(11, [$66,$F2,$0F,$38,$F1,$D9                           ] , 'crc32  ebx,cx'                                    );
  TestCase.testcase(12, [$F2,$0F,$38,$F1,$D9                               ] , 'crc32  ebx,ecx'                                   );
  TestCase.testcase(13, [$F2,$48,$0F,$38,$F1,$D9                           ] , 'crc32  rbx,rcx'                                   );
  TestCase.testcase(14, [$66,$0F,$38,$37,$01                               ] , 'pcmpgtq  xmm0,oword [rcx]'                        );
  TestCase.testcase(15, [$66,$0F,$38,$37,$C1                               ] , 'pcmpgtq  xmm0,xmm1'                               );
  TestCase.testcase(16, [$66,$0F,$3A,$61,$01,$00                           ] , 'pcmpestri  xmm0,oword [rcx],0x0'                  );
  TestCase.testcase(17, [$66,$0F,$3A,$61,$C1,$00                           ] , 'pcmpestri  xmm0,xmm1,0x0'                         );
  TestCase.testcase(18, [$66,$0F,$3A,$60,$01,$01                           ] , 'pcmpestrm  xmm0,oword [rcx],0x1'                  );
  TestCase.testcase(19, [$66,$0F,$3A,$60,$C1,$01                           ] , 'pcmpestrm  xmm0,xmm1,0x1'                         );
  TestCase.testcase(20, [$66,$0F,$3A,$63,$01,$02                           ] , 'pcmpistri  xmm0,oword [rcx],0x2'                  );
  TestCase.testcase(21, [$66,$0F,$3A,$63,$C1,$02                           ] , 'pcmpistri  xmm0,xmm1,0x2'                         );
  TestCase.testcase(22, [$66,$0F,$3A,$62,$01,$03                           ] , 'pcmpistrm  xmm0,oword [rcx],0x3'                  );
  TestCase.testcase(23, [$66,$0F,$3A,$62,$C1,$03                           ] , 'pcmpistrm  xmm0,xmm1,0x3'                         );
  TestCase.testcase(24, [$66,$F3,$0F,$B8,$19                               ] , 'popcnt  bx,word [rcx]'                            );
  TestCase.testcase(25, [$F3,$0F,$B8,$19                                   ] , 'popcnt  ebx,dword [rcx]'                          );
  TestCase.testcase(26, [$F3,$48,$0F,$B8,$19                               ] , 'popcnt  rbx,qword [rcx]'                          );
  TestCase.testcase(27, [$66,$F3,$0F,$B8,$19                               ] , 'popcnt  bx,word [rcx]'                            );
  TestCase.testcase(28, [$F3,$0F,$B8,$19                                   ] , 'popcnt  ebx,dword [rcx]'                          );
  TestCase.testcase(29, [$F3,$48,$0F,$B8,$19                               ] , 'popcnt  rbx,qword [rcx]'                          );
  TestCase.testcase(30, [$66,$F3,$0F,$B8,$D9                               ] , 'popcnt  bx,cx'                                    );
  TestCase.testcase(31, [$F3,$0F,$B8,$D9                                   ] , 'popcnt  ebx,ecx'                                  );
  TestCase.testcase(32, [$F3,$48,$0F,$B8,$D9                               ] , 'popcnt  rbx,rcx'                                  );
  TestCase.testcase(33, [$66,$F3,$0F,$B8,$D9                               ] , 'popcnt  bx,cx'                                    );
  TestCase.testcase(34, [$F3,$0F,$B8,$D9                                   ] , 'popcnt  ebx,ecx'                                  );
  TestCase.testcase(35, [$F3,$48,$0F,$B8,$D9                               ] , 'popcnt  rbx,rcx'                                  );
  TestCase.testcase(36, [$F2,$0F,$38,$F0,$D9                               ] , 'crc32  ebx,cl'                                    );
  TestCase.testcase(37, [$F2,$48,$0F,$38,$F0,$D9                           ] , 'crc32  rbx,cl'                                    );
  TestCase.testcase(38, [$66,$F2,$0F,$38,$F1,$D9                           ] , 'crc32  ebx,cx'                                    );
  TestCase.testcase(39, [$F2,$0F,$38,$F1,$D9                               ] , 'crc32  ebx,ecx'                                   );
  TestCase.testcase(40, [$F2,$48,$0F,$38,$F1,$D9                           ] , 'crc32  rbx,rcx'                                   );
  TestCase.testcase(41, [$F2,$0F,$38,$F0,$19                               ] , 'crc32  ebx,byte [rcx]'                            );
  TestCase.testcase(42, [$66,$F2,$0F,$38,$F1,$19                           ] , 'crc32  ebx,word [rcx]'                            );
  TestCase.testcase(43, [$F2,$0F,$38,$F1,$19                               ] , 'crc32  ebx,dword [rcx]'                           );
  TestCase.testcase(44, [$F2,$48,$0F,$38,$F1,$19                           ] , 'crc32  rbx,qword [rcx]'                           );
  TestCase.testcase(45, [$F2,$0F,$38,$F0,$D9                               ] , 'crc32  ebx,cl'                                    );
  TestCase.testcase(46, [$F2,$48,$0F,$38,$F0,$D9                           ] , 'crc32  rbx,cl'                                    );
  TestCase.testcase(47, [$66,$F2,$0F,$38,$F1,$D9                           ] , 'crc32  ebx,cx'                                    );
  TestCase.testcase(48, [$F2,$0F,$38,$F1,$D9                               ] , 'crc32  ebx,ecx'                                   );
  TestCase.testcase(49, [$F2,$48,$0F,$38,$F1,$D9                           ] , 'crc32  rbx,rcx'                                   );
  TestCase.testcase(50, [$66,$0F,$38,$37,$01                               ] , 'pcmpgtq  xmm0,oword [rcx]'                        );
  TestCase.testcase(51, [$66,$0F,$38,$37,$C1                               ] , 'pcmpgtq  xmm0,xmm1'                               );
  TestCase.testcase(52, [$66,$0F,$3A,$61,$01,$00                           ] , 'pcmpestri  xmm0,oword [rcx],0x0'                  );
  TestCase.testcase(53, [$66,$0F,$3A,$61,$C1,$00                           ] , 'pcmpestri  xmm0,xmm1,0x0'                         );
  TestCase.testcase(54, [$66,$0F,$3A,$60,$01,$01                           ] , 'pcmpestrm  xmm0,oword [rcx],0x1'                  );
  TestCase.testcase(55, [$66,$0F,$3A,$60,$C1,$01                           ] , 'pcmpestrm  xmm0,xmm1,0x1'                         );
  TestCase.testcase(56, [$66,$0F,$3A,$63,$01,$02                           ] , 'pcmpistri  xmm0,oword [rcx],0x2'                  );
  TestCase.testcase(57, [$66,$0F,$3A,$63,$C1,$02                           ] , 'pcmpistri  xmm0,xmm1,0x2'                         );
  TestCase.testcase(58, [$66,$0F,$3A,$62,$01,$03                           ] , 'pcmpistrm  xmm0,oword [rcx],0x3'                  );
  TestCase.testcase(59, [$66,$0F,$3A,$62,$C1,$03                           ] , 'pcmpistrm  xmm0,xmm1,0x3'                         );
  TestCase.testcase(60, [$66,$F3,$0F,$B8,$19                               ] , 'popcnt  bx,word [rcx]'                            );
  TestCase.testcase(61, [$F3,$0F,$B8,$19                                   ] , 'popcnt  ebx,dword [rcx]'                          );
  TestCase.testcase(62, [$F3,$48,$0F,$B8,$19                               ] , 'popcnt  rbx,qword [rcx]'                          );
  TestCase.testcase(63, [$66,$F3,$0F,$B8,$19                               ] , 'popcnt  bx,word [rcx]'                            );
  TestCase.testcase(64, [$F3,$0F,$B8,$19                                   ] , 'popcnt  ebx,dword [rcx]'                          );
  TestCase.testcase(65, [$F3,$48,$0F,$B8,$19                               ] , 'popcnt  rbx,qword [rcx]'                          );
  TestCase.testcase(66, [$66,$F3,$0F,$B8,$D9                               ] , 'popcnt  bx,cx'                                    );
  TestCase.testcase(67, [$F3,$0F,$B8,$D9                                   ] , 'popcnt  ebx,ecx'                                  );
  TestCase.testcase(68, [$F3,$48,$0F,$B8,$D9                               ] , 'popcnt  rbx,rcx'                                  );
  TestCase.testcase(69, [$66,$F3,$0F,$B8,$D9                               ] , 'popcnt  bx,cx'                                    );
  TestCase.testcase(70, [$F3,$0F,$B8,$D9                                   ] , 'popcnt  ebx,ecx'                                  );
  TestCase.testcase(71, [$F3,$48,$0F,$B8,$D9                               ] , 'popcnt  rbx,rcx'                                  );
  TestCase.Stop();
  TestCase.SaveToFile('../../../log/x64.sse4_2.log');
end;

end.